### ISSUE TITLE
Player Occurrence Generation

### ISSUE THREAD

**Issue by lordlordy** [lordlordy/TrainingDiary#14]
If a player is added to a team after events have started the app should only generate event occurrences for that player from today.
More generally - is there ever a requirement to generate historic events. ie  should the logic take the start and end date of an event and generate events with the condition they can only be in the future. 

Thoughts ?

**Comment by acb203** [comment]
You might well start to work with a pupil and after a conversation with them they/you realise they'd done several other things in the past. If you were retrospectively looking back and tracking an injury it could be useful to do be able to historically populate. 

However would we need to create a safeguard, e.g. a warning popup 'you are about to create events in the past, are you sure you want to do this!'

**Comment by lordlordy** [comment]
This asks if you want to generate historic events.
