### ISSUE TITLE
Additional session measures and athlete input

### ISSUE THREAD

**Issue by acb203** [lordlordy/TrainingDiary#15]
While I think about it, eventually, a way to input 'enjoyment' should be a huge factor with regards to the well-being of the pupil. 

we should discuss more broadly eventual functions so that this app doesn't become TOO complicated.

**Comment by lordlordy** [comment]
Latest build has readings - these can be added to any player event occurrence (ie any session they do). The readings have been set up so you can create any you like. When you create them you specify the range of valid values though at the moment I do nothing with this. Eventually I will restrict the inputs to that range.

if this covers what you are looking for please test and close. If you need something more / different please comment below.
