### ISSUE TITLE
Error when trying to update a team name

### ISSUE THREAD

**Issue by acb203** [lordlordy/TrainingDiary#16]
<img width="1423" alt="Screenshot 2019-11-01 at 10 14 01" src="https://user-images.githubusercontent.com/56553313/68018429-07090580-fc91-11e9-99a1-53d753eee614.png">

**Comment by lordlordy** [comment]
Need the exact steps to re-create this. When I try to rename a team it works fine.

**Comment by acb203** [comment]
Hmm, this is perplexing me now. Which proves your point! I need to be clearer. It works fine as you describe. I'll close this for now and re-open if I find it again, but will be more specific.
