### ISSUE TITLE
Add Event button on Events page?

### ISSUE THREAD

**Issue by acb203** [lordlordy/TrainingDiary#17]
Seems like I feel I should be able to add an event from the events page itself?

**Comment by lordlordy** [comment]
Absolutely. Had noted this but not had time to add

**Comment by lordlordy** [comment]
Button added for new events.
Please test and then close this issue if all ok

**Comment by lordlordy** [comment]
added in latest build.
Andy - please test all ok and then close this

**Comment by acb203** [comment]
When I go to events page and click 'new event' I get the following
<img width="1023" alt="Screenshot 2019-11-07 at 21 15 00" src="https://user-images.githubusercontent.com/56553313/68428259-b5d2a780-01a3-11ea-861b-4ef57dc77e11.png">

**Comment by lordlordy** [comment]
this has now been fixed.
