### ISSUE TITLE
When trying to access 'status types' in admin drop down, I get this

### ISSUE THREAD

**Issue by acb203** [lordlordy/TrainingDiary#19]
<img width="1360" alt="Screenshot 2019-11-01 at 10 31 38" src="https://user-images.githubusercontent.com/56553313/68019169-f194db00-fc92-11e9-8c50-e11a9a147304.png">

**Comment by lordlordy** [comment]
which drop down ? When I try this from main menu (Ie Admin->Status Types) nothing happens. Still a bug but not this error

**Comment by lordlordy** [comment]
removed the menu item for now.
Need to discuss and decide on status at some point. At the moment they are hard coded (ie adding or removing a status would require a code change). If it is something useful we could add them to the database and that would allow you to add new statuses

**Comment by acb203** [comment]
ok I will have a think. Something like 'Fully fit' 'Modified training' 'Unable to train'

**Comment by lordlordy** [comment]
States have been added back and correctly integrated. There are two that the system needs at a minimum: "scheduled" and "completed" beyond that you are free to add any you like. 

Once you're happy with what's in the app please close this.
