### ISSUE TITLE
Player in 2 teams that are added to same event

### ISSUE THREAD

**Issue by lordlordy** [lordlordy/TrainingDiary#20]
Now we have added ability to have multiple teams with same event. If we have Player 1 in Team A and Team B and then both those teams are added to the same event then Player 1 will have that event there twice.

Logic needs to be updated to take account of this. Needs a fair bit of thought and discussion to get this right. May need a DB change so perhaps has to only be done in next version (ie not version used for scholars this half of the term).

**Comment by acb203** [comment]
Well, we'd need to make sure that it only registers once in their TSB graph essentially. We know that a player can't perform the same event twice. 

That said, we should have a 'training conflict' if a player is in a hockey squad and rugby squad and we are asking them to be at two separate training sessions simultaneously, it should ask which team we want them to participate in.

**Comment by lordlordy** [comment]
We latest change of DB Schema is it now a none issue.
