### ISSUE TITLE
Deleting Team in Event View

### ISSUE THREAD

**Issue by lordlordy** [lordlordy/TrainingDiary#24]
Currently this just removes the team from the event. This does not remove all the Team Event Occurrences or the player event occurrences.

I assume the logic here is it should remove them all.

Thoughts Andy ? 
This is part of a more general discussion about the logic of the app. For instance - if a player is added to a team mid season only future sessions should be created when generate is clicked. However, this still is potentially ambiguous - eg a player is added to team after the first session he attends.
NB - with the change to player occurrences being part of the event it would be possible to add a player directly to an event (rather than just a team) though this does add complexity to how the app works

**Comment by acb203** [comment]
ok i've just encountered this. I would like this to be able to remove those team and player occurrences. currently this button doesn't seem to work. so if I click delete a team in the event view, nothing seems to happen.

**Comment by lordlordy** [comment]
yep that button is not wire up as wasn't sure of the logic for it
Will add logic. This will add all event occurrences associated with this team. Will also need to remove any reference to this team from an event (makes sense!). NB - this means if there happens to be a event occurrence in the past associated with this team it will be removed. The only way around this is to prevent deleting if such a thing exists.

**Comment by lordlordy** [comment]
This is done. Please test and close this issue.

Question: do you want to be able to delete a team completely ? If so do you want to only delete it if there are no events or players ? or do you want to be able to delete it whatever and remove all event occurrences associated with it ?

**Comment by acb203** [comment]
I think on this we need to be able to keep previous event occurences for that team yet the option to delete the team (or maybe archive) for the housekeeping and usage of the app. 

E.g. say a coach puts on a new 'team' for a while - like a wicketkeeping or spin bowling lunchtime squad and then it doesn't run in another term, they could just get rid of it.

**Comment by lordlordy** [comment]
Not sure precisely what you mean about archiving. We could have a flag on a team as to whether it's currently active. Then split the view for active and inactive teams.

As we progress we will need to give views for each coach and let them amend them since the number of teams may get too numerous to show them all.
