### ISSUE TITLE
Add list of all event occurrences

### ISSUE THREAD

**Issue by lordlordy** [lordlordy/TrainingDiary#26]
Since event occurrence is where coach can edit attendance and TSS etc... it should be easier to get to this.

**Comment by lordlordy** [comment]
added under "events' drop down menu.

Ready for testing.

**Comment by acb203** [comment]
yep great idea - also good to see whats going on for a day or week. further down the line, if there was the option for more than just a 'list' view that would be great. Imagine just a Mon-Sun set of boxes with the sessions on those days in those boxes? 

I won't close this if a 'grid' view option is relatively easy to achieve.

**Comment by lordlordy** [comment]
Definitely want to have a calendar view eventually. Once I've figured out logging in and user accounts I'll look at sorting out a calendar. 

Will close this and raise enhancement for new feature
