### ISSUE TITLE
Coach page function

### ISSUE THREAD

**Issue by acb203** [lordlordy/TrainingDiary#8]
Is it possible to add simple registration option, that defaults to the whole squad attending, but names can be deleted if they don't attend session?

**Comment by lordlordy** [comment]
Need to discuss what you mean by registration. At the moment it assumes attendance by everyone on the squad.

**Comment by acb203** [comment]
Ok that's perfect. Just a screen within coaches header such as as
'attendance' that then brings up all the squad sessions they might have for
their teams and ability to go in and delete player occurrences from that
event.

**Comment by lordlordy** [comment]
latest build has something in place now. This gives a list for a training session / match with each player. You can set the status, comments, TSS for each player and save. The plan eventually is to provide some functionality so you can say set all players to 'Completed' but for now it's manual

**Comment by lordlordy** [comment]
Think this is now covered by issue #28.
Currently the process is that when events are created they have a state of 'scheduled'. When you look at a team event occurrence it lists everyone that should have attended and gives the option to change the state of all attends in one click - so could changed all to 'completed' in one go.
The automation of this needs to be done external to the app as it may run even if no one is using the app. Thats what issue #28 is. I'm hopeful to get that built and running on the serve in the next few weeks.
If you agree that #28 now covers this please close this issue.
