### ISSUE TITLE
Event Generator

### ISSUE THREAD

**Issue by acb203** [lordlordy/TrainingDiary#9]
Several squads will often share an event. E.g. u16A rugby will play the same block fixture as the 1st XV. Intsead of having to add the event separately to each team, it would be good to have the ability to select from the drop down if the event/fixture has already been made.

**Comment by lordlordy** [comment]
Good idea. Going to take a little thought about how to do it as it changes the underlying data model - I'd made the assumption of one team per event ... but clearly that was a mistake

**Comment by lordlordy** [comment]
this has been done in latest build.
Please test and close if all ok.

**Comment by acb203** [comment]
When I was testing this - I went from team screen view to click 'add event' and it gave me the following error. Same on any team. Note the workaround from events view and add team seems to work. 
<img width="1405" alt="Screenshot 2019-11-07 at 21 09 23" src="https://user-images.githubusercontent.com/56553313/68427982-1f9e8180-01a3-11ea-9009-9af6b97bd588.png">

**Comment by lordlordy** [comment]
This is now fixed
